// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Backend.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentWorkplace")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VacationRemaining")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Backend.Models.EmployeeSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SkillId");

                    b.ToTable("EmployeeSkills");
                });

            modelBuilder.Entity("Backend.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            IconPath = "/assets/icons/csharp.svg",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            IconPath = "/assets/icons/java.svg",
                            Name = "Java"
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            IconPath = "/assets/icons/python.svg",
                            Name = "Python"
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            IconPath = "/assets/icons/php.svg",
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            IconPath = "/assets/icons/go.svg",
                            Name = "Go"
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            IconPath = "/assets/icons/nodejs.svg",
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            IconPath = "/assets/icons/ruby.svg",
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            IconPath = "/assets/icons/html5.svg",
                            Name = "HTML5"
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            IconPath = "/assets/icons/css3.svg",
                            Name = "CSS3"
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            IconPath = "/assets/icons/javascript.svg",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 11,
                            Category = 2,
                            IconPath = "/assets/icons/typescript.svg",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 12,
                            Category = 2,
                            IconPath = "/assets/icons/vue.svg",
                            Name = "Vue.js"
                        },
                        new
                        {
                            Id = 13,
                            Category = 2,
                            IconPath = "/assets/icons/react.svg",
                            Name = "React"
                        },
                        new
                        {
                            Id = 14,
                            Category = 2,
                            IconPath = "/assets/icons/angular.svg",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 15,
                            Category = 2,
                            IconPath = "/assets/icons/blazor.svg",
                            Name = "Blazor"
                        },
                        new
                        {
                            Id = 16,
                            Category = 3,
                            IconPath = "/assets/icons/mssql.svg",
                            Name = "SQL Server"
                        },
                        new
                        {
                            Id = 17,
                            Category = 3,
                            IconPath = "/assets/icons/mysql.svg",
                            Name = "MySQL"
                        },
                        new
                        {
                            Id = 18,
                            Category = 3,
                            IconPath = "/assets/icons/postgresql.svg",
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 19,
                            Category = 3,
                            IconPath = "/assets/icons/sqlite.svg",
                            Name = "SQLite"
                        },
                        new
                        {
                            Id = 20,
                            Category = 3,
                            IconPath = "/assets/icons/oracle.svg",
                            Name = "Oracle"
                        },
                        new
                        {
                            Id = 21,
                            Category = 4,
                            IconPath = "/assets/icons/docker.svg",
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 22,
                            Category = 4,
                            IconPath = "/assets/icons/kubernetes.svg",
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = 23,
                            Category = 4,
                            IconPath = "/assets/icons/nginx.svg",
                            Name = "NGINX"
                        },
                        new
                        {
                            Id = 24,
                            Category = 4,
                            IconPath = "/assets/icons/apache.svg",
                            Name = "Apache"
                        },
                        new
                        {
                            Id = 25,
                            Category = 6,
                            IconPath = "/assets/icons/aws.svg",
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 26,
                            Category = 6,
                            IconPath = "/assets/icons/azure.svg",
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 27,
                            Category = 6,
                            IconPath = "/assets/icons/gcp.svg",
                            Name = "GCP"
                        },
                        new
                        {
                            Id = 28,
                            Category = 5,
                            IconPath = "/assets/icons/git.svg",
                            Name = "Git"
                        },
                        new
                        {
                            Id = 29,
                            Category = 5,
                            IconPath = "/assets/icons/github.svg",
                            Name = "GitHub"
                        },
                        new
                        {
                            Id = 30,
                            Category = 5,
                            IconPath = "/assets/icons/gitlab.svg",
                            Name = "GitLab"
                        },
                        new
                        {
                            Id = 31,
                            Category = 7,
                            IconPath = "/assets/icons/visualstudio.svg",
                            Name = "Visual Studio"
                        },
                        new
                        {
                            Id = 32,
                            Category = 7,
                            IconPath = "/assets/icons/vscode.svg",
                            Name = "VS Code"
                        },
                        new
                        {
                            Id = 33,
                            Category = 7,
                            IconPath = "/assets/icons/postman.svg",
                            Name = "Postman"
                        },
                        new
                        {
                            Id = 34,
                            Category = 7,
                            IconPath = "/assets/icons/figma.svg",
                            Name = "Figma"
                        });
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Backend.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.EmployeeSkill", b =>
                {
                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.Navigation("EmployeeSkills");
                });

            modelBuilder.Entity("Backend.Models.Skill", b =>
                {
                    b.Navigation("EmployeeSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
